name: sanukitest-desu
on: 
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen1"
      
  testjob2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen2"
  
  testjob3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen3" >> $GITHUB_STEP_SUMMARY     

  testjob4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Check the [documentation](https://qiita.com/yu-ichiro/items/b50ceb0008edc3c0312e) for more info." >> $GITHUB_STEP_SUMMARY    
   