name: sanuki4

on:
  workflow_dispatch

env:
  SANUKI1 : ${{ toJSON(github.event) }}
  SANUKI2 : ${{ github.event }}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        run: |
          echo "$SANUKI1"
          echo "$SANUKI2"
          
          
