name: sanukitest-desu
on: 
  push:
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen1"
      
  testjob2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen2"
  
  testjob3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen3"      
   