name: sanukitest-desu2
on: 
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen1"
      
  #ファイルアップロード
  testjob2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this is aaaa" > output.txt
          echo "this is bbbb" >> output.txt
      - uses: actions/upload-artifact@v3
        with:
          name: myatf
          path: ./output.txt
  
  #ジョブサマリーに展開用のHTML付けて出力
#  testjob3:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          cat <<EOF > sample_table.md
#          | 名前     | 年齢 | 職業     |
#          |----------|------|----------|
#          | 山田太郎 | 25   | エンジニア|
#          | 佐藤花子 | 30   | デザイナー|
#          | 田中一郎 | 28   | マーケティング|
#          EOF
#      
#          echo "<details>" \
#               "<summary>★開発者UNITテストのカバレッジを見る</summary>" \
#               "$(cat sample_table.md)" \
#               "</details>" >> $GITHUB_STEP_SUMMARY
  
  #ジョブサマリーに展開用のHTML付けて出力
  testjob4:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "| 名前     | 年齢 | 職業     |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "| 山田太郎 | 25   | エンジニア|" >> $GITHUB_STEP_SUMMARY
          echo "| 佐藤花子 | 30   | デザイナー|" >> $GITHUB_STEP_SUMMARY
          echo "| 田中一郎 | 28   | マーケティング|" >> $GITHUB_STEP_SUMMARY
  
   